import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from '../types';
import { resizeImageToAspectRatio } from './imageUtils';

export const generateBoothImage = async (
  imageBase64: string,
  promptTemplate: string,
  apiKey: string,
  referenceImageBase64?: string,
  aspectRatio?: AspectRatio,
  modelName?: string,
  resolution?: '1K' | '2K' | '4K'
): Promise<string> => {
  if (!apiKey || apiKey.trim() === '') {
    throw new Error("Gemini API Key missing. Please configure it in Settings.");
  }

  const ai = new GoogleGenAI({ apiKey });

  // Sanitize base64 strings
  const cleanBase64 = imageBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');
  const cleanRefBase64 = referenceImageBase64?.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');

  // Map AspectRatio to Gemini API format
  const mapAspectRatioToGemini = (ratio?: AspectRatio): string => {
    switch (ratio) {
      case '3:4':
        return '3:4';
      case '4:3':
        return '4:3';
      case '9:16':
        return '9:16';
      case '16:9':
        return '16:9';
      case 'square':
      default:
        return '1:1';
    }
  };

  // Get aspect ratio specifications for prompt (descriptive text)
  const getAspectRatioSpec = (ratio?: AspectRatio): string => {
    switch (ratio) {
      case '3:4':
        return 'portrait orientation with 3:4 aspect ratio (width 768px, height 1024px)';
      case '4:3':
        return 'landscape orientation with 4:3 aspect ratio (width 1024px, height 768px)';
      case '9:16':
        return 'portrait orientation with 9:16 aspect ratio (width 576px, height 1024px)';
      case '16:9':
        return 'landscape orientation with 16:9 aspect ratio (width 1024px, height 576px)';
      case 'square':
      default:
        return 'square aspect ratio (1024px × 1024px)';
    }
  };

  try {
    const model = modelName || 'gemini-3-pro-image-preview';
    const geminiAspectRatio = mapAspectRatioToGemini(aspectRatio);
    const geminiResolution = resolution || '1K';

    const aspectRatioSpec = getAspectRatioSpec(aspectRatio);

    // Construct prompt
    let finalPrompt = `
      Transform the person in the first image into the following style: ${promptTemplate}.
      Maintain the person's facial features and identity strictly, but change the clothing, background, and artistic style to match the description.
      CRITICAL: The output image MUST be in ${aspectRatioSpec}. The composition must fit this exact aspect ratio.
      High quality, photorealistic or stylized as requested.
    `;

    const parts: any[] = [
      {
        inlineData: {
          mimeType: 'image/jpeg',
          data: cleanBase64
        }
      }
    ];

    // If a reference style image exists, add it to the request
    if (cleanRefBase64) {
      parts.push({
        inlineData: {
          mimeType: 'image/jpeg',
          data: cleanRefBase64
        }
      });
      finalPrompt += " Use the second image as a strict style reference for color palette, lighting, and composition.";
    }

    parts.push({ text: finalPrompt });

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: parts
      },
      config: {
        aspectRatio: geminiAspectRatio,
        resolution: geminiResolution
      }
    });

    // Extract image from response
    // The response might contain text or image. We look for the inlineData.
    const resultParts = response.candidates?.[0]?.content?.parts;

    let generatedImage: string | null = null;

    if (resultParts) {
      for (const part of resultParts) {
        if (part.inlineData && part.inlineData.data) {
          generatedImage = `data:image/jpeg;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!generatedImage) {
      throw new Error("No image generated by the model.");
    }

    if (aspectRatio && aspectRatio !== 'square') {
      console.log(`🖼️ Resizing generated image to ${aspectRatio} aspect ratio...`);
      generatedImage = await resizeImageToAspectRatio(generatedImage, aspectRatio);
    }

    return generatedImage;

  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};