import { GoogleGenAI } from "@google/genai";

export const generateBoothImage = async (
  imageBase64: string,
  promptTemplate: string,
  eventContext: string,
  apiKey: string,
  referenceImageBase64?: string
): Promise<string> => {
  if (!apiKey || apiKey.trim() === '') {
    throw new Error("Gemini API Key missing. Please configure it in Settings.");
  }

  const ai = new GoogleGenAI({ apiKey });

  // Sanitize base64 strings
  const cleanBase64 = imageBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');
  const cleanRefBase64 = referenceImageBase64?.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');

  try {
    const model = 'gemini-2.5-flash-image';
    
    // Construct prompt
    let finalPrompt = `
      Transform the person in the first image into the following style: ${promptTemplate}.
      Context: ${eventContext}.
      Maintain the person's facial features and identity strictly, but change the clothing, background, and artistic style to match the description.
      High quality, photorealistic or stylized as requested.
    `;

    const parts: any[] = [
      {
        inlineData: {
          mimeType: 'image/jpeg',
          data: cleanBase64
        }
      }
    ];

    // If a reference style image exists, add it to the request
    if (cleanRefBase64) {
      parts.push({
        inlineData: {
          mimeType: 'image/jpeg',
          data: cleanRefBase64
        }
      });
      finalPrompt += " Use the second image as a strict style reference for color palette, lighting, and composition.";
    }

    parts.push({ text: finalPrompt });

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: parts
      },
      config: {
        // We do not set responseMimeType for image generation models like nano banana
      }
    });

    // Extract image from response
    // The response might contain text or image. We look for the inlineData.
    const resultParts = response.candidates?.[0]?.content?.parts;
    
    if (resultParts) {
      for (const part of resultParts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:image/jpeg;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};