/*
# One-Time-Use QR Access Codes

## Summary
Adds a per-event toggle for one-time-use QR access codes. When enabled, organizers
can generate batches of unique QR codes. Each code grants kiosk entry to the event
exactly once — the redemption is atomic so two simultaneous scans of the same QR
cannot both succeed. After entry, the existing per-device photo limits take over.

## New Columns on `events`
- `qr_access_enabled` (boolean, default false): Toggle to enable/disable one-time
  QR access for an event. When false, the event uses its normal passcode-based entry.

## New Table: `event_access_codes`
Stores unique one-time-use access tokens for events.
- `id` (uuid, primary key)
- `event_id` (uuid, FK to events, ON DELETE CASCADE)
- `token` (text, unique, not null): The unique access token embedded in the QR code URL
- `is_used` (boolean, not null, default false): Whether this code has been redeemed
- `redeemed_at` (timestamptz, nullable): When the code was redeemed
- `redeemed_ip` (text, nullable): IP address of the device that redeemed the code
- `redeemed_device_token` (text, nullable): Browser token of the redeeming device
- `created_at` (timestamptz, default now())
- `batch_id` (uuid, nullable): Groups codes generated in the same batch

## Security (RLS)
- RLS enabled on `event_access_codes`.
- SELECT: Event owners can read their own event's access codes (checked via events.user_id).
- INSERT: Event owners can insert codes for their own events.
- UPDATE: Only the service role (via edge function) can update codes for redemption.
  Event owners cannot directly update — redemption must go through the edge function
  for atomic safety.
- DELETE: Event owners can delete (revoke) codes for their own events.

## Indexes
- Index on `event_id` for listing codes per event.
- Index on `token` for fast lookup during redemption.
- Index on `event_id, is_used` for counting used vs unused.

## Important Notes
1. QR access is OFF by default. Existing events are unaffected.
2. Only the edge function (service role) can mark a code as used, ensuring atomic
   redemption that cannot be bypassed from the browser.
3. Each token is a cryptographically random string generated by the edge function
   or the backend service, making codes unguessable.
4. Codes are never reused — once `is_used` is true, the code is permanently consumed.
*/

-- 1. Add qr_access_enabled column to events
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS qr_access_enabled boolean NOT NULL DEFAULT false;

-- 2. Create event_access_codes table
CREATE TABLE IF NOT EXISTS event_access_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  token text NOT NULL,
  is_used boolean NOT NULL DEFAULT false,
  redeemed_at timestamptz,
  redeemed_ip text,
  redeemed_device_token text,
  created_at timestamptz NOT NULL DEFAULT now(),
  batch_id uuid DEFAULT gen_random_uuid(),
  UNIQUE(token)
);

-- 3. Enable RLS
ALTER TABLE event_access_codes ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- Event owners can read their own event's access codes
DROP POLICY IF EXISTS "select_own_event_access_codes" ON event_access_codes;
CREATE POLICY "select_own_event_access_codes"
ON event_access_codes FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM events
    WHERE events.id = event_access_codes.event_id
    AND events.user_id = auth.uid()
  )
);

-- Event owners can insert codes for their own events
DROP POLICY IF EXISTS "insert_own_event_access_codes" ON event_access_codes;
CREATE POLICY "insert_own_event_access_codes"
ON event_access_codes FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM events
    WHERE events.id = event_access_codes.event_id
    AND events.user_id = auth.uid()
  )
);

-- Event owners can delete (revoke) codes for their own events
DROP POLICY IF EXISTS "delete_own_event_access_codes" ON event_access_codes;
CREATE POLICY "delete_own_event_access_codes"
ON event_access_codes FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM events
    WHERE events.id = event_access_codes.event_id
    AND events.user_id = auth.uid()
  )
);

-- Note: UPDATE is NOT granted to anon or authenticated.
-- Only the service role (used in the edge function) can update codes for redemption,
-- ensuring atomic one-time-use enforcement that cannot be bypassed from the browser.

-- 5. Indexes
CREATE INDEX IF NOT EXISTS idx_event_access_codes_event_id
  ON event_access_codes(event_id);

CREATE INDEX IF NOT EXISTS idx_event_access_codes_token
  ON event_access_codes(token);

CREATE INDEX IF NOT EXISTS idx_event_access_codes_event_used
  ON event_access_codes(event_id, is_used);